// src/lib/constants/achievements.ts
export const ACHIEVEMENT_TYPES = {
    LESSONS_COMPLETED: 'lessons_completed',
    STREAK_DAYS: 'streak_days',
    POINTS_TOTAL: 'points_total',
    MODULES_COMPLETED: 'modules_completed',
    ATTENDANCE_COUNT: 'attendance_count',
};
export const ACHIEVEMENT_CATEGORIES = {
    INICIANTE: 'iniciante',
    APRENDIZADO: 'aprendizado',
    DISCIPLINA: 'disciplina',
    MAESTRIA: 'maestria',
    SOCIAL: 'social',
};
export const ACHIEVEMENT_SEEDS = [
    {
        name: 'Primeiro Passo',
        description: 'Complete sua primeira lição',
        requirement_type: 'lessons_completed',
        requirement_value: 1,
        points_reward: 10,
        category: 'iniciante',
        badge_icon: '🎯',
        badge_color: '#84CC16',
    },
    {
        name: 'Estudante Dedicado',
        description: 'Complete 5 lições',
        requirement_type: 'lessons_completed',
        requirement_value: 5,
        points_reward: 25,
        category: 'aprendizado',
        badge_icon: '📚',
        badge_color: '#4F46E5',
    },
    {
        name: 'Fogo Sagrado',
        description: 'Mantenha 3 dias de streak consecutivos',
        requirement_type: 'streak_days',
        requirement_value: 3,
        points_reward: 30,
        category: 'disciplina',
        badge_icon: '🔥',
        badge_color: '#EF4444',
    },
    {
        name: 'Persistente',
        description: 'Mantenha 7 dias de streak consecutivos',
        requirement_type: 'streak_days',
        requirement_value: 7,
        points_reward: 50,
        category: 'disciplina',
        badge_icon: '⚡',
        badge_color: '#F59E0B',
    },
    {
        name: 'Aprendiz Persistente',
        description: 'Complete 10 lições',
        requirement_type: 'lessons_completed',
        requirement_value: 10,
        points_reward: 50,
        category: 'aprendizado',
        badge_icon: '🌟',
        badge_color: '#8B5CF6',
    },
    {
        name: 'Mestre Músico',
        description: 'Complete 50 lições',
        requirement_type: 'lessons_completed',
        requirement_value: 50,
        points_reward: 200,
        category: 'maestria',
        badge_icon: '👑',
        badge_color: '#F59E0B',
    },
];
