import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cn } from '@/lib/utils';
import { ROLE_CONFIG, DESIGN_UTILS } from '@/lib/constants/design';
export const OrientalContainer = ({ role, children, showHeader = true, showPhilosophy = false, title, subtitle, className, }) => {
    const config = ROLE_CONFIG[role];
    const background = DESIGN_UTILS.backgrounds[role];
    return (_jsxs("div", { className: cn('min-h-screen', background, className), children: [showHeader && (_jsxs("div", { className: "relative overflow-hidden", children: [_jsx("div", { className: "absolute inset-0 opacity-5", children: _jsx("div", { className: "absolute inset-0 bg-gradient-to-r from-transparent via-current to-transparent transform -skew-y-1", style: { color: config.color } }) }), _jsx("div", { className: "relative px-6 py-8 sm:px-8 lg:px-12", children: _jsxs("div", { className: "max-w-7xl mx-auto", children: [_jsxs("div", { className: "flex items-center gap-4 mb-6", children: [_jsx("div", { className: "text-6xl font-bold opacity-20", style: { color: config.color }, children: config.japanese.character }), _jsxs("div", { children: [_jsx("h1", { className: "text-3xl sm:text-4xl lg:text-5xl font-bold text-gray-900", children: title || `Dashboard ${config.japanese.title}` }), _jsx("p", { className: "text-lg text-gray-600 mt-2", children: subtitle || config.japanese.subtitle }), showPhilosophy && (_jsx("p", { className: "text-sm text-gray-500 mt-4 italic", children: config.philosophy }))] })] }), _jsxs("div", { className: "flex items-center gap-2 text-sm text-gray-600", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-3 h-3 rounded-full", style: { backgroundColor: config.color } }), _jsx("span", { className: "capitalize", children: role })] }), _jsx("span", { className: "text-gray-400", children: "\u2022" }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx("span", { children: "Densidade:" }), _jsx("span", { className: "font-medium capitalize", style: { color: config.color }, children: config.density })] }), _jsx("span", { className: "text-gray-400", children: "\u2022" }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx("span", { children: "Estilo:" }), _jsx("span", { className: "font-medium capitalize", style: { color: config.color }, children: config.dashboardStyle })] })] })] }) })] })), _jsx("div", { className: "px-6 py-8 sm:px-8 lg:px-12", children: _jsx("div", { className: "max-w-7xl mx-auto", children: children }) }), _jsx("div", { className: "mt-auto px-6 py-4 sm:px-8 lg:px-12", children: _jsx("div", { className: "max-w-7xl mx-auto", children: _jsxs("div", { className: "flex items-center justify-between text-xs text-gray-400", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("span", { children: "\u00A9 2024 Nipo School" }), _jsx("span", { children: "\u2022" }), _jsx("span", { children: "Sistema Oriental Unificado" })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { children: "Filosofia:" }), _jsx("span", { className: "font-medium", style: { color: config.color }, children: role === 'student' ? 'Wabi-Sabi' : role === 'professor' ? 'Zen' : 'Kaizen' })] })] }) }) })] }));
};
// Layouts específicos por papel
export const StudentLayout = ({ children }) => (_jsx(OrientalContainer, { role: "student", showPhilosophy: true, title: "Centro de Estudos", subtitle: "Sua jornada musical come\u00E7a aqui", children: children }));
export const ProfessorLayout = ({ children }) => (_jsx(OrientalContainer, { role: "professor", title: "\u00C1rea dos Professores", subtitle: "Ferramentas pedag\u00F3gicas organizadas", children: children }));
export const AdminLayout = ({ children }) => (_jsx(OrientalContainer, { role: "admin", title: "Painel Administrativo", subtitle: "Controle total e inteligente", children: children }));
